%import common.SIGNED_NUMBER
//%import common.CNAME
%import common.LETTER
%import common.DIGIT
//%import common.NEWLINE
%import common.WS
%import common.ESCAPED_STRING
%import common.CPP_COMMENT
%import common.C_COMMENT

%ignore WS

COMMENT: CPP_COMMENT | C_COMMENT
%ignore COMMENT

BOOL: "true" | "false"
IDENT: /(?!(if|else|while|for|break|continue|return|true|false))/ LETTER (LETTER | DIGIT | "_")*

literal: SIGNED_NUMBER | ESCAPED_STRING | BOOL
ident: IDENT

?lvalue: ident

?inc_dec: "--" lvalue -> prefix_dec
    | "++" lvalue -> prefix_inc
    | lvalue "--" -> suffix_dec
    | lvalue "++" -> suffix_inc

?primary: literal
    | inc_dec
    | lvalue
    | "(" expr ")"
    | call

call: ident "(" (expr ("," expr)*)? ")"

?unary: primary
    | "+" unary -> plus
    | "-" unary -> minus
    | "!" unary -> not

?mult: unary
    | mult "*" unary    -> mul
    | mult "/" unary    -> div
    | mult "%" unary    -> mod

?add: mult
    | add "+" mult      -> add
    | add "-" mult      -> sub

?compare: add
    | add ">" add         -> gt
    | add ">=" add        -> ge
    | add "<" add         -> lt
    | add "<=" add        -> le

?equals: compare
    | compare "==" compare -> eq
    | compare "!=" compare -> ne

?logic_and: equals
    | logic_and "&&" equals

?logic_or: logic_and
    | logic_or "||" logic_and

?expr: logic_or

?expr_or_empty: expr
    | -> empty_expr

type: ident

ident_assign: ident "=" expr -> assign
assign: lvalue "=" expr -> assign

vars_decl: type (ident | ident_assign) ("," (ident | ident_assign))*

?simple_stmt: call
    | assign
    | vars_decl
    | "return" expr? -> return
    | "break" -> break
    | "continue" -> continue

?stmt: simple_stmt ";"
    | "{" stmt_list "}" -> block
    | "if" "(" expr ")" stmp_or_empty ("else" stmp_or_empty)? -> if
    | "while" "(" expr ")" stmp_or_empty -> while
    | "for" "(" for_stmt_list ";" expr_or_empty ";" for_stmt_list ")" stmp_or_empty  -> for
    | func
    | inc_dec

?stmp_or_empty: stmt
    | ";" -> stmt_list

func_param: type ident -> vars_decl
func: type ident "(" (func_param ("," func_param)*)? ")" "{" stmt_list "}"

?stmt_list: (stmt ";"*)*
?for_stmt_list: vars_decl
    | (simple_stmt ("," simple_stmt)*)? -> stmt_list

?prog: stmt_list

?start: prog
