%import common.NUMBER
%import common.CNAME
%import common.NEWLINE
%import common.WS
%import common.ESCAPED_STRING

%ignore WS

COMMENT: "/*" /.*?/s "*/"
       | "//" /.*/ NEWLINE
%ignore COMMENT

num: NUMBER
ident: CNAME
string: ESCAPED_STRING
sq_string: /'[^']*'/

?type: "char"   -> type_simple_char
     | "int"    -> type_simple_int
     | "bool"   -> type_simple_bool
     | "string" -> type_simple_string
     | "double" -> type_simple_double
     | "float"  -> type_simple_float
     | "void"   -> type_simple_void
     | ident    -> type_custom

create_var: type var_decl ("," var_decl)*

?var_decl: ident -> var_decl_simple
         | ident "[" "]" -> var_decl_array
         | ident "=" rvalue -> var_init
         | ident "[" "]" "=" rvalue -> var_init_array

?lvalue: ident
       | postfix_expr "[" rvalue "]" -> array_subscr
       | postfix_expr "." ident -> access

?rvalue: assign_expr

?assign_expr: ternary
            | lvalue "=" assign_expr -> assign
            | lvalue "+=" assign_expr -> assign_add
            | lvalue "-=" assign_expr -> assign_sub
            | lvalue "*=" assign_expr -> assign_mul
            | lvalue "/=" assign_expr -> assign_div
            | lvalue "//=" assign_expr -> assign_idv
            | lvalue "%=" assign_expr -> assign_mod

?ternary: logic_or
        | logic_or "?" ternary ":" ternary

?logic_or: logic_and
         | logic_or "||" logic_and

?logic_and: compare_eq
          | logic_and "&&" compare_eq

?compare_eq: compare
           | compare_eq "==" compare -> comp_eq
           | compare_eq "!=" compare -> comp_nq

?compare: add
        | compare "<" add -> comp_lt
        | compare ">" add -> comp_gt
        | compare "<=" add -> comp_le
        | compare ">=" add -> comp_ge

?add: mult
    | add "+" mult -> add
    | add "-" mult -> sub

?mult: unary
     | mult "*" unary -> mul
     | mult "/" unary -> div
     | mult "//" unary -> idv
     | mult "%" unary -> mod

?unary: prefix
      | "+" unary -> unary_inc
      | "-" unary -> unary_dec
      | "!" unary -> logic_not

?prefix: postfix_expr
       | "++" prefix -> prefix_inc
       | "--" prefix -> prefix_dec

?postfix_expr: primary
             | postfix_expr "[" rvalue "]" -> array_subscr
             | postfix_expr "." ident -> access
             | postfix_expr "(" call_arg_list ")" -> func_call
             | postfix_expr "++" -> postfix_inc
             | postfix_expr "--" -> postfix_dec

?primary: num
        | string
        | sq_string
        | ident
        | "(" rvalue ")"

call_arg_list: (rvalue ("," rvalue)*)?

param_decl: type ident
          | type ident "[" "]" -> array_param_decl

param_list: (param_decl ("," param_decl)*)?

?func_def: type ident "(" param_list ")" body

struct_def: "struct" ident body

?stmt_misc: "break" -> stmt_break
          | "continue" -> stmt_continue
          | "return" rvalue? -> stmt_return

?stmt: rvalue
     | create_var
     | stmt_misc
     | struct_def

?stmt_closed: stmt ";"

?body: "{" stmt_list "}"

?for_init: create_var
         | rvalue
         | // empty

?for_cond: rvalue
         | // empty

?for_next: rvalue
         | // empty

?condition: "if" "(" rvalue ")" (stmt_closed | condition | body) ("else" (stmt_closed | condition | body))? -> condition_if
          | "while" "(" rvalue ")" (stmt_closed | condition | body) -> condition_while
          | "do" (stmt_closed | condition | body) "while" "(" rvalue ")" ";" -> condition_do_while
          | "for" "(" for_init ";" for_cond ";" for_next ")" (stmt_closed | condition | body) -> condition_for

?stmt_general: stmt_closed
             | condition
             | func_def

?stmt_list: (stmt_general ";"*)*

?prog: stmt_list

?start: prog
